FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /src

COPY . .

WORKDIR /src/TM.API

RUN dotnet restore 

RUN dotnet publish -c Release -o /app


FROM mcr.microsoft.com/dotnet/aspnet:9.0

COPY --from=build /app . 

EXPOSE 80

ENTRYPOINT [ "dotnet", "TM.API.dll" ]